Fix minify step of release build due to issue of classes of..
..jaudiotagger
Error
> Task :app:minifyReleaseWithR8 FAILED
ERROR: R8: Missing class java.awt.image.BufferedImage (referenced from: java.lang.Object org.jaudiotagger.tag.images.StandardArtwork.getImage() and 1 other context)
Missing class javax.imageio.ImageIO (referenced from: java.lang.Object org.jaudiotagger.tag.images.StandardArtwork.getImage())
Missing class javax.imageio.stream.ImageInputStream (referenced from: java.lang.Object org.jaudiotagger.tag.images.StandardArtwork.getImage())

Also temporarily disable "Full Mode" in gradle.properties